# 1-Librerias

In [43]:



# importamos librerias necesarias
import pandas as pd
import numpy as np


import datetime
import time


import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
# opcion de pandas para ver todas las columnas de un dataframe sin puntos suspensivos
pd.set_option('display.max_columns', None)

import warnings
warnings.filterwarnings('ignore')

# 2-Carga de datos

In [44]:
df = pd.read_csv("../data/finanzas-hotel-bookings-limpio.csv")
df

,hotel,market_segment,distribution_channel,agent,company,previous_cancellations,previous_bookings_not_canceled,booking_changes,is_canceled,reservation_status,reservation_status_date,arrival_date,arrival_date_week_number,diferencia_dias,overnight_stays,stays_in_weekend_nights,stays_in_week_nights,country,latitud,longitud,is_repeated_guest,adults,children,babies,number_of_guests,customer_type,days_in_waiting_list,lead_time,reserved_room_type,assigned_room_type,meal,required_car_parking_spaces,total_of_special_requests,adr
0,Resort Hotel,Direct,Direct,250,sin identificar,0,0,1,Not Canceled,Check-Out,2015-07-07,2015-07-01,27,6,6,2,4,Portugal,39.662165,-8.135352,0,2,0,0,2,Transient,0,72,A,A,BB,0,1,84.67
1,Resort Hotel,Direct,Direct,250,sin identificar,0,0,1,Not Canceled,Check-Out,2015-07-07,2015-07-01,27,6,6,2,4,Portugal,39.662165,-8.135352,0,2,0,0,2,Transient,0,72,D,D,BB,0,1,99.67
2,Resort Hotel,Offline TA/TO,TA/TO,5,sin identificar,0,0,0,Not Canceled,Check-Out,2015-08-07,2015-07-01,27,37,7,2,5,Portugal,39.662165,-8.135352,0,2,0,0,2,Transient,0,78,D,D,BB,1,0,63.60
3,Resort Hotel,Offline TA/TO,TA/TO,8,sin identificar,0,0,0,Not Canceled,Check-Out,2015-08-07,2015-07-01,27,37,7,2,5,Ireland,52.865196,-7.979460,0,2,0,0,2,Contract,0,48,D,D,BB,0,0,79.50
4,Resort Hotel,Online TA,TA/TO,240,sin identificar,0,0,0,Not Canceled,Check-Out,2015-08-07,2015-07-01,27,37,7,2,5,Portugal,39.662165,-8.135352,0,2,0,0,2,Transient,0,77,A,A,BB,0,0,94.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71197,City Hotel,Direct,Direct,sin identificar,sin identificar,0,0,0,Canceled,No-Show,2015-11-12,2015-12-11,50,-29,7,2,5,Angola,-11.877577,17.569124,0,1,0,0,1,Transient,0,2,E,E,BB,0,1,104.00
71198,City Hotel,Corporate,Corporate,sin identificar,219,0,5,0,Canceled,No-Show,2016-09-11,2016-11-09,46,-59,1,0,1,Portugal,39.662165,-8.135352,1,1,0,0,1,Transient,0,6,D,D,BB,0,1,94.00
71199,City Hotel,Corporate,Corporate,sin identificar,219,0,10,0,Canceled,No-Show,2016-02-11,2016-11-02,45,-265,1,0,1,Portugal,39.662165,-8.135352,1,1,0,0,1,Transient,0,26,A,E,BB,0,1,88.00
71200,City Hotel,Aviation,Corporate,sin identificar,153,0,1,0,Canceled,No-Show,2017-01-02,2017-02-01,5,-30,0,0,0,Austria,47.593970,14.124560,1,1,0,0,1,Transient,0,1,A,A,BB,0,1,0.00
71201,City Hotel,Corporate,Corporate,sin identificar,40,0,0,0,Canceled,No-Show,2017-02-08,2017-08-02,31,-175,2,0,2,Portugal,39.662165,-8.135352,1,1,0,0,1,Transient,0,0,A,C,BB,0,1,65.00

# 3-Analisis descriptivo

In [45]:
# describe solo para las columnas numericas 
df_descriptivo = df.describe().T 
df_descriptivo.style.background_gradient()

In [46]:
# describe las variables categoricas 
df.describe(include="object").T

                         count unique              top   freq
hotel                    71202      2       City Hotel  43471
market_segment           71202      8        Online TA  42064
distribution_channel     71202      5            TA/TO  56405
agent                    71202    320                9  23416
company                  71202    331  sin identificar  66830
is_canceled              71202      2     Not Canceled  52173
reservation_status       71202      3        Check-Out  52173
reservation_status_date  71202    901       2016-02-14    205
arrival_date             71202    793       2017-07-15    202
country                  69955    169         Portugal  22265
customer_type            71202      4        Transient  58462
reserved_room_type       71202     10                A  46177
assigned_room_type       71202     11                A  37856
meal                     71202      5               BB  55302

In [47]:
# selecionamos las columnas de tipo object
df_categoricas = df[df.select_dtypes(include="object").columns.tolist()]
df_categoricas.head(3)

,hotel,market_segment,distribution_channel,agent,company,is_canceled,reservation_status,reservation_status_date,arrival_date,country,customer_type,reserved_room_type,assigned_room_type,meal
0,Resort Hotel,Direct,Direct,250,sin identificar,Not Canceled,Check-Out,2015-07-07,2015-07-01,Portugal,Transient,A,A,BB
1,Resort Hotel,Direct,Direct,250,sin identificar,Not Canceled,Check-Out,2015-07-07,2015-07-01,Portugal,Transient,D,D,BB
2,Resort Hotel,Offline TA/TO,TA/TO,5,sin identificar,Not Canceled,Check-Out,2015-08-07,2015-07-01,Portugal,Transient,D,D,BB

In [42]:
# usando px para graficar 
df_sucio = df_categoricas.copy()    
df_sucio["room_modification"] = np.where(df_sucio["reserved_room_type"] == df_sucio["assigned_room_type"], "Si", "No")
df_sucio

,hotel,market_segment,distribution_channel,agent,company,is_canceled,reservation_status,reservation_status_date,arrival_date,country,customer_type,reserved_room_type,assigned_room_type,meal,room_modification
0,Resort Hotel,Direct,Direct,250,sin identificar,Not Canceled,Check-Out,2015-07-07,2015-07-01,Portugal,Transient,A,A,BB,Si
1,Resort Hotel,Direct,Direct,250,sin identificar,Not Canceled,Check-Out,2015-07-07,2015-07-01,Portugal,Transient,D,D,BB,Si
2,Resort Hotel,Offline TA/TO,TA/TO,5,sin identificar,Not Canceled,Check-Out,2015-08-07,2015-07-01,Portugal,Transient,D,D,BB,Si
3,Resort Hotel,Offline TA/TO,TA/TO,8,sin identificar,Not Canceled,Check-Out,2015-08-07,2015-07-01,Ireland,Contract,D,D,BB,Si
4,Resort Hotel,Online TA,TA/TO,240,sin identificar,Not Canceled,Check-Out,2015-08-07,2015-07-01,Portugal,Transient,A,A,BB,Si
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71197,City Hotel,Direct,Direct,sin identificar,sin identificar,Canceled,No-Show,2015-11-12,2015-12-11,Angola,Transient,E,E,BB,Si
71198,City Hotel,Corporate,Corporate,sin identificar,219,Canceled,No-Show,2016-09-11,2016-11-09,Portugal,Transient,D,D,BB,Si
71199,City Hotel,Corporate,Corporate,sin identificar,219,Canceled,No-Show,2016-02-11,2016-11-02,Portugal,Transient,A,E,BB,No
71200,City Hotel,Aviation,Corporate,sin identificar,153,Canceled,No-Show,2017-01-02,2017-02-01,Austria,Transient,A,A,BB,Si
71201,City Hotel,Corporate,Corporate,sin identificar,40,Canceled,No-Show,2017-02-08,2017-08-02,Portugal,Transient,A,C,BB,No

In [ ]:
# emoezamos con el analisis de cancelaciones de hoteles