# 1-Librerias

In [14]:
import pandas as pd
import numpy as np

# opcion de pandas para ver todas las columnas de un dataframe sin puntos suspensivos
pd.set_option('display.max_columns', None)

# 2-Carga de datos

In [19]:
df = pd.read_csv("../data/finanzas-hotel-bookings.csv")
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,NaN,NaN,0,Transient,0.0,0,0,Check-Out,1/07/15
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,NaN,NaN,0,Transient,0.0,0,0,Check-Out,1/07/15
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2/07/15
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2/07/15
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,240.0,NaN,0,Transient,98.0,0,1,Check-Out,3/07/15

# 3-Analisis previo

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  agent                           103050 non-null  float64
 23  company                         6797 non-null    float64
 24  days_in_waiting_list            119390 non-null  int64
 25  customer_type                   119390 non-null  object
 26  adr                             119390 non-null  float64
 27  required_car_parking_spaces     119390 non-null  int64
 28  total_of_special_requests       119390 non-null  int64
 29  reservation_status              119390 non-null  object
 30  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(11)
memory usage: 28.2+ MB

In [17]:
df_descriptivo = df.describe().T # describe solo para las columnas numericas 
df_descriptivo

,count,mean,std,min,25%,50%,75%,max
is_canceled,119390.0,0.370416,0.482918,0.00,0.00,0.000,1.0,1.0
lead_time,119390.0,104.011416,106.863097,0.00,18.00,69.000,160.0,737.0
arrival_date_year,119390.0,2016.156554,0.707476,2015.00,2016.00,2016.000,2017.0,2017.0
arrival_date_week_number,119390.0,27.165173,13.605138,1.00,16.00,28.000,38.0,53.0
arrival_date_day_of_month,119390.0,15.798241,8.780829,1.00,8.00,16.000,23.0,31.0
stays_in_weekend_nights,119390.0,0.927599,0.998613,0.00,0.00,1.000,2.0,19.0
stays_in_week_nights,119390.0,2.500302,1.908286,0.00,1.00,2.000,3.0,50.0
adults,119390.0,1.856403,0.579261,0.00,2.00,2.000,2.0,55.0
children,119386.0,0.103890,0.398561,0.00,0.00,0.000,0.0,10.0
babies,119390.0,0.007949,0.097436,0.00,0.00,0.000,0.0,10.0
is_repeated_guest,119390.0,0.031912,0.175767,0.00,0.00,0.000,0.0,1.0
previous_cancellations,119390.0,0.087118,0.844336,0.00,0.00,0.000,0.0,26.0
previous_bookings_not_canceled,119390.0,0.137097,1.497437,0.00,0.00,0.000,0.0,72.0
booking_changes,119390.0,0.221124,0.652306,0.00,0.00,0.000,0.0,21.0
agent,103050.0,86.693382,110.774548,1.00,9.00,14.000,229.0,535.0
company,6797.0,189.266735,131.655015,6.00,62.00,179.000,270.0,543.0
days_in_waiting_list,119390.0,2.321149,17.594721,0.00,0.00,0.000,0.0,391.0
adr,119390.0,101.831122,50.535790,-6.38,69.29,94.575,126.0,5400.0
required_car_parking_spaces,119390.0,0.062518,0.245291,0.00,0.00,0.000,0.0,8.0
total_of_special_requests,119390.0,0.571363,0.792798,0.00,0.00,0.000,1.0,5.0

In [18]:
df_descriptivo = df.describe().T
df_descriptivo

,count,mean,std,min,25%,50%,75%,max
is_canceled,119390.0,0.370416,0.482918,0.00,0.00,0.000,1.0,1.0
lead_time,119390.0,104.011416,106.863097,0.00,18.00,69.000,160.0,737.0
arrival_date_year,119390.0,2016.156554,0.707476,2015.00,2016.00,2016.000,2017.0,2017.0
arrival_date_week_number,119390.0,27.165173,13.605138,1.00,16.00,28.000,38.0,53.0
arrival_date_day_of_month,119390.0,15.798241,8.780829,1.00,8.00,16.000,23.0,31.0
stays_in_weekend_nights,119390.0,0.927599,0.998613,0.00,0.00,1.000,2.0,19.0
stays_in_week_nights,119390.0,2.500302,1.908286,0.00,1.00,2.000,3.0,50.0
adults,119390.0,1.856403,0.579261,0.00,2.00,2.000,2.0,55.0
children,119386.0,0.103890,0.398561,0.00,0.00,0.000,0.0,10.0
babies,119390.0,0.007949,0.097436,0.00,0.00,0.000,0.0,10.0
is_repeated_guest,119390.0,0.031912,0.175767,0.00,0.00,0.000,0.0,1.0
previous_cancellations,119390.0,0.087118,0.844336,0.00,0.00,0.000,0.0,26.0
previous_bookings_not_canceled,119390.0,0.137097,1.497437,0.00,0.00,0.000,0.0,72.0
booking_changes,119390.0,0.221124,0.652306,0.00,0.00,0.000,0.0,21.0
agent,103050.0,86.693382,110.774548,1.00,9.00,14.000,229.0,535.0
company,6797.0,189.266735,131.655015,6.00,62.00,179.000,270.0,543.0
days_in_waiting_list,119390.0,2.321149,17.594721,0.00,0.00,0.000,0.0,391.0
adr,119390.0,101.831122,50.535790,-6.38,69.29,94.575,126.0,5400.0
required_car_parking_spaces,119390.0,0.062518,0.245291,0.00,0.00,0.000,0.0,8.0
total_of_special_requests,119390.0,0.571363,0.792798,0.00,0.00,0.000,1.0,5.0

## 3.1-Analisis de Nulos

In [7]:
## calculamos el porcentaje de nulos
df_descriptivo["count"] = ((df_descriptivo["count"]/df.shape[0])*100).round(2)

## ronombramos la columna count por % nulos 
df_descriptivo.rename(columns={"count": "% nulos"}, inplace=True)
df_descriptivo

,% nulos,mean,std,min,25%,50%,75%,max
is_canceled,100.00,0.370416,0.482918,0.00,0.00,0.000,1.0,1.0
lead_time,100.00,104.011416,106.863097,0.00,18.00,69.000,160.0,737.0
arrival_date_year,100.00,2016.156554,0.707476,2015.00,2016.00,2016.000,2017.0,2017.0
arrival_date_week_number,100.00,27.165173,13.605138,1.00,16.00,28.000,38.0,53.0
arrival_date_day_of_month,100.00,15.798241,8.780829,1.00,8.00,16.000,23.0,31.0
stays_in_weekend_nights,100.00,0.927599,0.998613,0.00,0.00,1.000,2.0,19.0
stays_in_week_nights,100.00,2.500302,1.908286,0.00,1.00,2.000,3.0,50.0
adults,100.00,1.856403,0.579261,0.00,2.00,2.000,2.0,55.0
children,100.00,0.103890,0.398561,0.00,0.00,0.000,0.0,10.0
babies,100.00,0.007949,0.097436,0.00,0.00,0.000,0.0,10.0
is_repeated_guest,100.00,0.031912,0.175767,0.00,0.00,0.000,0.0,1.0
previous_cancellations,100.00,0.087118,0.844336,0.00,0.00,0.000,0.0,26.0
previous_bookings_not_canceled,100.00,0.137097,1.497437,0.00,0.00,0.000,0.0,72.0
booking_changes,100.00,0.221124,0.652306,0.00,0.00,0.000,0.0,21.0
agent,86.31,86.693382,110.774548,1.00,9.00,14.000,229.0,535.0
company,5.69,189.266735,131.655015,6.00,62.00,179.000,270.0,543.0
days_in_waiting_list,100.00,2.321149,17.594721,0.00,0.00,0.000,0.0,391.0
adr,100.00,101.831122,50.535790,-6.38,69.29,94.575,126.0,5400.0
required_car_parking_spaces,100.00,0.062518,0.245291,0.00,0.00,0.000,0.0,8.0
total_of_special_requests,100.00,0.571363,0.792798,0.00,0.00,0.000,1.0,5.0

## 3.2-Analisis de Dupliacados

In [13]:
# numero de duplicados
df.duplicated().sum()

0

In [9]:
# porcentaje de duplicados 
(df.duplicated().sum()/df.shape[0]).round(2)*100

27.0

In [10]:
#  registros duplicados 
df_duplicados = df[df.duplicated()]
df_duplicados

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,240.0,NaN,0,Transient,98.00,0,1,Check-Out,3/07/15
22,Resort Hotel,0,72,2015,July,27,1,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,250.0,NaN,0,Transient,84.67,0,1,Check-Out,7/07/15
43,Resort Hotel,0,70,2015,July,27,2,2,3,2,0.0,0,HB,ROU,Direct,Direct,0,0,0,E,E,0,250.0,NaN,0,Transient,137.00,0,1,Check-Out,7/07/15
138,Resort Hotel,1,5,2015,July,28,5,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,240.0,NaN,0,Transient,97.00,0,0,Canceled,1/07/15
200,Resort Hotel,0,0,2015,July,28,7,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,240.0,NaN,0,Transient,109.80,0,3,Check-Out,8/07/15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119349,City Hotel,0,186,2017,August,35,31,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,9.0,NaN,0,Transient,126.00,0,2,Check-Out,3/09/17
119352,City Hotel,0,63,2017,August,35,31,0,3,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,3/09/17
119353,City Hotel,0,63,2017,August,35,31,0,3,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,3/09/17
119354,City Hotel,0,63,2017,August,35,31,0,3,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,9.0,NaN,0,Transient-Party,195.33,0,2,Check-Out,3/09/17
119373,City Hotel,0,175,2017,August,35,31,1,3,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,42.0,NaN,0,Transient,82.35,0,1,Check-Out,4/09/17

In [12]:
# eliminar duplicados 
df.drop_duplicates(inplace=True)
# reseteamos el index
df.reset_index(drop=True, inplace=True)
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,NaN,NaN,0,Transient,0.00,0,0,Check-Out,1/07/15
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,NaN,NaN,0,Transient,0.00,0,0,Check-Out,1/07/15
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2/07/15
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2/07/15
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,240.0,NaN,0,Transient,98.00,0,1,Check-Out,3/07/15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87386,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,394.0,NaN,0,Transient,96.14,0,0,Check-Out,6/09/17
87387,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,9.0,NaN,0,Transient,225.43,0,2,Check-Out,7/09/17
87388,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,9.0,NaN,0,Transient,157.71,0,4,Check-Out,7/09/17
87389,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,89.0,NaN,0,Transient,104.40,0,0,Check-Out,7/09/17
87390,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,9.0,NaN,0,Transient,151.20,0,2,Check-Out,7/09/17

## 3.3-Analisis de DateTime

In [20]:

# creamos la columna de datre arrival a partir de las tres columnas de arrival
df["arrival_date"] = df["arrival_date_year"].astype(str) + "-" + df["arrival_date_month"] + "-" + df["arrival_date_day_of_month"].astype(str)
df["arrival_date"] = pd.to_datetime(df["arrival_date"])
df.drop(columns=["arrival_date_year", "arrival_date_month", "arrival_date_day_of_month"], inplace=True)

# cambiamos el formato de las fechas de arrival_date a datetime con formato dia mes año 
df["arrival_date"] = pd.to_datetime(df["arrival_date"], format="%d/%B/%Y")
df["reservation_status_date"] = pd.to_datetime(df["reservation_status_date"])
df

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-01-07,2015-07-01
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-01-07,2015-07-01
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-02-07,2015-07-01
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-02-07,2015-07-01
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-03-07,2015-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-06-09,2017-08-30
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-07-09,2017-08-31
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-07-09,2017-08-31
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-07-09,2017-08-31
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-07-09,2017-08-29

In [21]:
# Se apriecian discrepancias sobre las fechas de "reservation_status_date","arrival_date"
df[["reservation_status_date","arrival_date"]].sample(40)

       reservation_status_date arrival_date
90345               2016-05-06   2016-06-03
102237              2016-11-25   2016-11-24
65048               2015-10-21   2017-03-23
55093               2016-04-23   2016-08-04
113421              2017-07-06   2017-06-05
17247               2015-10-29   2015-11-20
111163              2017-07-05   2017-05-05
30199               2016-11-16   2016-11-15
116789              2017-07-25   2017-07-21
8535                2016-02-09   2016-10-05
7640                2016-08-08   2016-08-18
21504               2016-02-03   2016-03-01
70927               2017-05-24   2017-06-25
17055               2015-09-23   2015-09-22
72937               2017-03-08   2017-08-10
105340              2017-05-02   2017-02-02
61175               2016-11-14   2016-12-03
105824              2017-02-16   2017-02-15
100212              2016-10-25   2016-10-23
102898              2016-08-12   2016-12-08
77133               2015-09-09   2015-09-06
3535                2015-12-29   2015-12-22
94916               2016-12-08   2016-08-11
44600               2015-12-10   2015-10-08
47773               2016-02-25   2016-03-03
56524               2015-10-21   2016-09-08
4401                2016-01-29   2016-03-12
7151                2016-07-13   2016-07-24
17625               2015-10-18   2015-10-15
21089               2016-02-18   2016-02-13
91126               2016-06-17   2016-06-15
24669               2016-05-30   2016-05-19
94986               2016-08-13   2016-08-10
90168               2016-03-06   2016-05-31
92577               2016-09-07   2016-07-07
111790              2017-05-15   2017-05-09
25111               2016-06-15   2016-06-01
19781               2016-03-01   2015-12-31
82650               2016-04-01   2015-12-30
114954              2017-06-29   2017-06-23

In [22]:
# Creamos una columna con la diferencia de dias entre arrival_date y reservation_status_date 
df["diferencia_dias"] = (df["reservation_status_date"] - df["arrival_date"]).dt.days
df.sample(10)

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date,diferencia_dias
47921,City Hotel,1,62,11,0,4,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,9.0,NaN,0,Transient,63.75,0,0,Canceled,2016-01-28,2016-03-09,-41
25247,Resort Hotel,0,43,25,1,4,2,2.0,0,BB,FRA,Online TA,TA/TO,0,0,0,G,G,0,240.0,NaN,0,Transient,201.00,1,1,Check-Out,2016-06-20,2016-06-15,5
257,Resort Hotel,0,37,28,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,C,C,0,105.0,NaN,0,Transient,120.00,0,1,Check-Out,2015-07-13,2015-07-10,3
69172,City Hotel,1,102,21,1,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,9.0,NaN,0,Transient,149.33,0,0,Canceled,2017-05-04,2017-05-26,-22
4615,Resort Hotel,1,106,13,1,3,2,0.0,0,FB,PRT,Groups,Direct,0,0,0,A,A,0,68.0,NaN,0,Transient,84.00,0,0,Canceled,2016-01-22,2016-03-24,-62
106677,City Hotel,0,67,9,2,1,1,1.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,7.0,NaN,0,Transient,73.46,0,2,Check-Out,2017-01-03,2017-02-26,-54
61062,City Hotel,1,290,49,1,3,2,0.0,0,BB,SVK,Online TA,TA/TO,0,0,0,D,D,0,9.0,NaN,0,Transient,86.70,0,0,Canceled,2016-10-27,2016-12-01,-35
13099,Resort Hotel,1,134,31,1,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,240.0,NaN,0,Transient,224.00,0,1,Canceled,2017-03-21,2017-07-31,-132
47580,City Hotel,1,3,9,4,6,2,0.0,0,HB,SAU,Online TA,TA/TO,0,0,0,D,D,0,9.0,NaN,0,Transient-Party,150.80,0,0,No-Show,2016-02-27,2016-02-27,0
39023,Resort Hotel,0,45,31,0,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,1,242.0,NaN,0,Transient,263.33,0,2,Check-Out,2017-06-08,2017-08-03,-56

In [23]:
# para futuros podria ser interesante analizar este conjunto de datosa en los que los dias de diferencia son negativos. Posible fraude ????
df_dataq = df[df["diferencia_dias"] < 0]
df_dataq

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date,diferencia_dias
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-01-07,2015-07-01,-175
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-01-07,2015-07-01,-175
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-02-07,2015-07-01,-144
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-02-07,2015-07-01,-144
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-03-07,2015-07-01,-116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-06-09,2017-08-30,-82
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-07-09,2017-08-31,-53
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-07-09,2017-08-31,-53
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-07-09,2017-08-31,-53
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-07-09,2017-08-29,-51

In [24]:
# eliminamos los registros con diferencia de dias negativa o dicho de otra forma sobre escribimos aquellos registros con diferencia de dias positiva
df_final = df[df["diferencia_dias"] >= 0]
df_final.head()

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date,diferencia_dias
21,Resort Hotel,0,72,27,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07,2015-07-01,6
22,Resort Hotel,0,72,27,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07,2015-07-01,6
23,Resort Hotel,0,72,27,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,250.0,NaN,0,Transient,99.67,0,1,Check-Out,2015-07-07,2015-07-01,6
25,Resort Hotel,0,78,27,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,5.0,NaN,0,Transient,63.60,1,0,Check-Out,2015-08-07,2015-07-01,37
26,Resort Hotel,0,48,27,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,8.0,NaN,0,Contract,79.50,0,0,Check-Out,2015-08-07,2015-07-01,37

In [25]:
# parece raro que algunos registros de la columnas diferencia_dias sea positiva, indicaria que la fecha de cancelacion seria posterior al de llegada. por lo que agregaremos los registros a df_dataq para analizarlos mas adelante. 
# de la misma manera procederemos a agregar aquellos registros de df_dataq que tengan la fecha de cancelacion anterior a la de llegada.

df_cancelaciones_positivas = df_final[df_final["reservation_status"]== "Canceled"]
df_cancelaciones_positivas.head()

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date,diferencia_dias
27,Resort Hotel,1,60,27,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,240.0,NaN,0,Transient,107.0,0,2,Canceled,2015-11-05,2015-07-01,127
71,Resort Hotel,1,101,27,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,240.0,NaN,0,Transient,73.8,0,1,Canceled,2015-12-06,2015-07-03,156
74,Resort Hotel,1,51,27,0,2,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,242.0,NaN,0,Transient,110.3,0,0,Canceled,2015-09-06,2015-07-03,65
83,Resort Hotel,1,81,27,3,7,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,2,250.0,NaN,0,Transient,124.0,0,1,Canceled,2015-09-06,2015-07-03,65
105,Resort Hotel,1,26,27,2,5,2,2.0,0,BB,PRT,Online TA,TA/TO,0,0,0,H,H,0,240.0,NaN,0,Transient,163.0,0,0,Canceled,2015-09-06,2015-07-04,64

In [116]:
df_cancelaciones_negativas = df_dataq[df_dataq["reservation_status"] == "Canceled"]
df_cancelaciones_negativas.head()

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date,diferencia_dias
7,Resort Hotel,1,85,27,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-06-05,2015-07-01,-26
8,Resort Hotel,1,75,27,0,3,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22,2015-07-01,-70
9,Resort Hotel,1,23,27,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,240.0,NaN,0,Transient,123.0,0,0,Canceled,2015-06-23,2015-07-01,-8
30,Resort Hotel,1,96,27,2,8,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,E,0,NaN,NaN,0,Transient,108.3,0,2,Canceled,2015-05-29,2015-07-01,-33
32,Resort Hotel,1,45,27,1,3,3,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,241.0,NaN,0,Transient,108.8,0,1,Canceled,2015-05-19,2015-07-02,-44

In [117]:
# actualiozamos los registros de df_final sin los datos de df_cancelaciones_positivas
df_final = df_final[df_final["reservation_status"]!= "Canceled"]
df_final.head()

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date,diferencia_dias
20,Resort Hotel,0,72,27,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07,2015-07-01,6
21,Resort Hotel,0,72,27,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,250.0,NaN,0,Transient,99.67,0,1,Check-Out,2015-07-07,2015-07-01,6
23,Resort Hotel,0,78,27,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,5.0,NaN,0,Transient,63.60,1,0,Check-Out,2015-08-07,2015-07-01,37
24,Resort Hotel,0,48,27,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,8.0,NaN,0,Contract,79.50,0,0,Check-Out,2015-08-07,2015-07-01,37
26,Resort Hotel,0,77,27,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,240.0,NaN,0,Transient,94.00,0,0,Check-Out,2015-08-07,2015-07-01,37

In [118]:
df_dataq = df_dataq[df_dataq["reservation_status"] != "Canceled"]
df_dataq.head()

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date,diferencia_dias
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-01-07,2015-07-01,-175
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-01-07,2015-07-01,-175
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-02-07,2015-07-01,-144
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-02-07,2015-07-01,-144
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-03-07,2015-07-01,-116

In [119]:
# concatenamos los datos de df_dataq y df_cancelaciones_positivas
df_dataq = pd.concat([df_dataq, df_cancelaciones_positivas])
df_final = pd.concat([df_final, df_cancelaciones_negativas])

In [120]:
df_final

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date,diferencia_dias
20,Resort Hotel,0,72,27,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07,2015-07-01,6
21,Resort Hotel,0,72,27,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,250.0,NaN,0,Transient,99.67,0,1,Check-Out,2015-07-07,2015-07-01,6
23,Resort Hotel,0,78,27,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,5.0,NaN,0,Transient,63.60,1,0,Check-Out,2015-08-07,2015-07-01,37
24,Resort Hotel,0,48,27,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,8.0,NaN,0,Contract,79.50,0,0,Check-Out,2015-08-07,2015-07-01,37
26,Resort Hotel,0,77,27,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,240.0,NaN,0,Transient,94.00,0,0,Check-Out,2015-08-07,2015-07-01,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70754,City Hotel,1,1,4,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,1,3,A,A,0,NaN,40.0,0,Transient,65.00,0,1,Canceled,2017-01-23,2017-01-24,-1
76842,City Hotel,1,14,21,0,1,1,0.0,0,BB,PRT,Complementary,Direct,1,1,3,A,A,0,NaN,45.0,0,Transient,0.00,0,1,Canceled,2017-05-22,2017-05-24,-2
77439,City Hotel,1,1,24,2,1,1,0.0,0,BB,ITA,Aviation,Corporate,1,1,2,D,D,0,NaN,153.0,0,Transient,110.00,0,0,Canceled,2017-06-16,2017-06-17,-1
77906,City Hotel,1,13,22,1,2,1,0.0,0,BB,SWE,Direct,Direct,1,1,1,A,A,0,NaN,NaN,0,Transient,95.00,0,0,Canceled,2017-05-17,2017-05-29,-12
80677,City Hotel,1,4,23,1,0,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,4,A,A,0,NaN,238.0,0,Transient,65.00,0,0,Canceled,2017-05-06,2017-06-05,-30

## 3.3.1-Analisis de DateTime para reservation_status

- Analisis del ultimo estado de la reserva No-Show - el cliente no se ha registrado y ha informado al hotel del motivo

In [60]:
toto = pd.DataFrame(df[df["reservation_status"] == "No-Show"]["diferencia_dias"])

# importamos seaborn
import seaborn as sns
# hacemos una histograma con plotly express 
import plotly.express as px
fig = px.histogram(toto, x="diferencia_dias", nbins=100)
fig.show()

Tampoco parece tener sentido mantener aquellos registros que reflejen una notificacion de aquellos clientes que no se han registrado pese a que lo notifiquen dias despues de su supesta llegada en el df_final.

In [91]:
filtro1 = df["reservation_status"]=="No-Show"
filtro2 = df["diferencia_dias"] < 0

df[filtro1 & filtro2]

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date,diferencia_dias
119,Resort Hotel,1,36,27,0,1,1,0.0,0,BB,PRT,Direct,Direct,0,0,0,E,G,1,250.0,NaN,0,Transient,123.00,0,0,No-Show,2015-04-07,2015-07-04,-88
1469,Resort Hotel,1,48,36,2,8,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,G,I,0,250.0,NaN,0,Transient,153.00,0,0,No-Show,2015-03-09,2015-09-03,-178
1512,Resort Hotel,1,94,36,2,5,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,G,G,0,NaN,NaN,0,Transient,153.00,0,0,No-Show,2015-05-09,2015-09-05,-119
1571,Resort Hotel,1,144,37,3,7,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,240.0,NaN,0,Transient,75.96,0,0,No-Show,2015-07-09,2015-09-07,-60
2134,Resort Hotel,1,77,41,0,3,2,2.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,250.0,NaN,0,Transient,66.00,0,2,No-Show,2015-08-10,2015-10-08,-59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56255,City Hotel,1,2,50,2,5,1,0.0,0,BB,AGO,Direct,Direct,0,0,0,E,E,0,NaN,NaN,0,Transient,104.00,0,1,No-Show,2015-11-12,2015-12-11,-29
59793,City Hotel,1,6,46,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,5,D,D,0,NaN,219.0,0,Transient,94.00,0,1,No-Show,2016-09-11,2016-11-09,-59
61857,City Hotel,1,26,45,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,10,A,E,0,NaN,219.0,0,Transient,88.00,0,1,No-Show,2016-02-11,2016-11-02,-265
75076,City Hotel,1,1,5,0,0,1,0.0,0,BB,AUT,Aviation,Corporate,1,0,1,A,A,0,NaN,153.0,0,Transient,0.00,0,1,No-Show,2017-01-02,2017-02-01,-30
85609,City Hotel,1,0,31,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,0,A,C,0,NaN,40.0,0,Transient,65.00,0,1,No-Show,2017-02-08,2017-08-02,-175

## 4-Filtrado de datos 

Tras tener claro cuales son los datos del objeto de estudio procedemos a la creacion de filtros para quedarnos solo con aquellos datos de valor.

In [19]:


# cancelaciones realizadas antes de la fecha de llegada, por lo que se procede a agregarlos a df_final
filtro1 = df["reservation_status"]=="Canceled"
filtro2 = df["diferencia_dias"] < 0

df_canceled = df[filtro1 & filtro2]

In [20]:
# clientes que hicieron checout y tienen valores positivos en diferencia de dias , por lo que se procede a agregarlos a df_final
filtro1 = df["reservation_status"]=="Check-Out"
filtro2 = df["diferencia_dias"] >= 0

df_checkout = df[filtro1 & filtro2]

In [21]:
# clientes que notificaron que no se registrarian en el hotel antes de su llegada teniendo positivos en diferencia de dias , por lo que se procede a agregarlos a df_final
filtro1 = df["reservation_status"]=="No-Show"
filtro2 = df["diferencia_dias"] < 0

df_noshow = df[filtro1 & filtro2]

In [22]:
# concatenacion de dataframes 
df_final = pd.concat([df_checkout, df_canceled, df_noshow])
df_final

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_date,diferencia_dias
20,Resort Hotel,0,72,27,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07,2015-07-01,6
21,Resort Hotel,0,72,27,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,D,D,1,250.0,NaN,0,Transient,99.67,0,1,Check-Out,2015-07-07,2015-07-01,6
23,Resort Hotel,0,78,27,2,5,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,D,D,0,5.0,NaN,0,Transient,63.60,1,0,Check-Out,2015-08-07,2015-07-01,37
24,Resort Hotel,0,48,27,2,5,2,0.0,0,BB,IRL,Offline TA/TO,TA/TO,0,0,0,D,D,0,8.0,NaN,0,Contract,79.50,0,0,Check-Out,2015-08-07,2015-07-01,37
26,Resort Hotel,0,77,27,2,5,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,240.0,NaN,0,Transient,94.00,0,0,Check-Out,2015-08-07,2015-07-01,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56255,City Hotel,1,2,50,2,5,1,0.0,0,BB,AGO,Direct,Direct,0,0,0,E,E,0,NaN,NaN,0,Transient,104.00,0,1,No-Show,2015-11-12,2015-12-11,-29
59793,City Hotel,1,6,46,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,5,D,D,0,NaN,219.0,0,Transient,94.00,0,1,No-Show,2016-09-11,2016-11-09,-59
61857,City Hotel,1,26,45,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,10,A,E,0,NaN,219.0,0,Transient,88.00,0,1,No-Show,2016-02-11,2016-11-02,-265
75076,City Hotel,1,1,5,0,0,1,0.0,0,BB,AUT,Aviation,Corporate,1,0,1,A,A,0,NaN,153.0,0,Transient,0.00,0,1,No-Show,2017-01-02,2017-02-01,-30
85609,City Hotel,1,0,31,0,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,0,A,C,0,NaN,40.0,0,Transient,65.00,0,1,No-Show,2017-02-08,2017-08-02,-175

In [23]:
# reordenamos las columnas 
df_final = df_final[['hotel', 
                         'previous_cancellations',
                         'previous_bookings_not_canceled', 
                         'booking_changes',               
                         'is_canceled', 
                         'reservation_status', 
                         'reservation_status_date', 
                         'arrival_date',
                         'arrival_date_week_number',
                         'diferencia_dias',

                         'stays_in_weekend_nights',
                         'stays_in_week_nights',

                         'country', 
                         'is_repeated_guest', 
                         'adults', 
                         'children',
                         'babies',
                         'customer_type', 
                         'days_in_waiting_list', 
                         'lead_time',    
                         
                         'market_segment', 
                         'distribution_channel',
                         'agent', 
                         'company',

                         'reserved_room_type',
                         'assigned_room_type', 
                         'meal', 
                         'required_car_parking_spaces', 
                         'total_of_special_requests',

                         'adr']]

df_final

,hotel,previous_cancellations,previous_bookings_not_canceled,booking_changes,is_canceled,reservation_status,reservation_status_date,arrival_date,arrival_date_week_number,diferencia_dias,stays_in_weekend_nights,stays_in_week_nights,country,is_repeated_guest,adults,children,babies,customer_type,days_in_waiting_list,lead_time,market_segment,distribution_channel,agent,company,reserved_room_type,assigned_room_type,meal,required_car_parking_spaces,total_of_special_requests,adr
20,Resort Hotel,0,0,1,0,Check-Out,2015-07-07,2015-07-01,27,6,2,4,PRT,0,2,0.0,0,Transient,0,72,Direct,Direct,250.0,NaN,A,A,BB,0,1,84.67
21,Resort Hotel,0,0,1,0,Check-Out,2015-07-07,2015-07-01,27,6,2,4,PRT,0,2,0.0,0,Transient,0,72,Direct,Direct,250.0,NaN,D,D,BB,0,1,99.67
23,Resort Hotel,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,2,5,PRT,0,2,0.0,0,Transient,0,78,Offline TA/TO,TA/TO,5.0,NaN,D,D,BB,1,0,63.60
24,Resort Hotel,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,2,5,IRL,0,2,0.0,0,Contract,0,48,Offline TA/TO,TA/TO,8.0,NaN,D,D,BB,0,0,79.50
26,Resort Hotel,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,2,5,PRT,0,2,0.0,0,Transient,0,77,Online TA,TA/TO,240.0,NaN,A,A,BB,0,0,94.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56255,City Hotel,0,0,0,1,No-Show,2015-11-12,2015-12-11,50,-29,2,5,AGO,0,1,0.0,0,Transient,0,2,Direct,Direct,NaN,NaN,E,E,BB,0,1,104.00
59793,City Hotel,0,5,0,1,No-Show,2016-09-11,2016-11-09,46,-59,0,1,PRT,1,1,0.0,0,Transient,0,6,Corporate,Corporate,NaN,219.0,D,D,BB,0,1,94.00
61857,City Hotel,0,10,0,1,No-Show,2016-02-11,2016-11-02,45,-265,0,1,PRT,1,1,0.0,0,Transient,0,26,Corporate,Corporate,NaN,219.0,A,E,BB,0,1,88.00
75076,City Hotel,0,1,0,1,No-Show,2017-01-02,2017-02-01,5,-30,0,0,AUT,1,1,0.0,0,Transient,0,1,Aviation,Corporate,NaN,153.0,A,A,BB,0,1,0.00
85609,City Hotel,0,0,0,1,No-Show,2017-02-08,2017-08-02,31,-175,0,2,PRT,1,1,0.0,0,Transient,0,0,Corporate,Corporate,NaN,40.0,A,C,BB,0,1,65.00

## 5-Creacion de columna noches de estancia; overnight_stays.

In [24]:
# creamos la columna overnight stays  sumando  los valores stays_in_weekend_nights y stays_in_week_nights
df_final["overnight_stays"] = df_final["stays_in_weekend_nights"] + df_final["stays_in_week_nights"]
df_final

/var/folders/k2/06hcsvc50xgflbnr685ttflc0000gn/T/ipykernel_22938/4125081376.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final["overnight_stays"] = df_final["stays_in_weekend_nights"] + df_final["stays_in_week_nights"]

,hotel,previous_cancellations,previous_bookings_not_canceled,booking_changes,is_canceled,reservation_status,reservation_status_date,arrival_date,arrival_date_week_number,diferencia_dias,stays_in_weekend_nights,stays_in_week_nights,country,is_repeated_guest,adults,children,babies,customer_type,days_in_waiting_list,lead_time,market_segment,distribution_channel,agent,company,reserved_room_type,assigned_room_type,meal,required_car_parking_spaces,total_of_special_requests,adr,overnight_stays
20,Resort Hotel,0,0,1,0,Check-Out,2015-07-07,2015-07-01,27,6,2,4,PRT,0,2,0.0,0,Transient,0,72,Direct,Direct,250.0,NaN,A,A,BB,0,1,84.67,6
21,Resort Hotel,0,0,1,0,Check-Out,2015-07-07,2015-07-01,27,6,2,4,PRT,0,2,0.0,0,Transient,0,72,Direct,Direct,250.0,NaN,D,D,BB,0,1,99.67,6
23,Resort Hotel,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,2,5,PRT,0,2,0.0,0,Transient,0,78,Offline TA/TO,TA/TO,5.0,NaN,D,D,BB,1,0,63.60,7
24,Resort Hotel,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,2,5,IRL,0,2,0.0,0,Contract,0,48,Offline TA/TO,TA/TO,8.0,NaN,D,D,BB,0,0,79.50,7
26,Resort Hotel,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,2,5,PRT,0,2,0.0,0,Transient,0,77,Online TA,TA/TO,240.0,NaN,A,A,BB,0,0,94.00,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56255,City Hotel,0,0,0,1,No-Show,2015-11-12,2015-12-11,50,-29,2,5,AGO,0,1,0.0,0,Transient,0,2,Direct,Direct,NaN,NaN,E,E,BB,0,1,104.00,7
59793,City Hotel,0,5,0,1,No-Show,2016-09-11,2016-11-09,46,-59,0,1,PRT,1,1,0.0,0,Transient,0,6,Corporate,Corporate,NaN,219.0,D,D,BB,0,1,94.00,1
61857,City Hotel,0,10,0,1,No-Show,2016-02-11,2016-11-02,45,-265,0,1,PRT,1,1,0.0,0,Transient,0,26,Corporate,Corporate,NaN,219.0,A,E,BB,0,1,88.00,1
75076,City Hotel,0,1,0,1,No-Show,2017-01-02,2017-02-01,5,-30,0,0,AUT,1,1,0.0,0,Transient,0,1,Aviation,Corporate,NaN,153.0,A,A,BB,0,1,0.00,0
85609,City Hotel,0,0,0,1,No-Show,2017-02-08,2017-08-02,31,-175,0,2,PRT,1,1,0.0,0,Transient,0,0,Corporate,Corporate,NaN,40.0,A,C,BB,0,1,65.00,2

In [25]:
# creamnos la columna number_of_guests sumando los valores de adults, children y babies
df_final["number_of_guests"] = df_final["adults"] + df_final["children"] + df_final["babies"]
df_final

/var/folders/k2/06hcsvc50xgflbnr685ttflc0000gn/T/ipykernel_22938/1699397585.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final["number_of_guests"] = df_final["adults"] + df_final["children"] + df_final["babies"]

,hotel,previous_cancellations,previous_bookings_not_canceled,booking_changes,is_canceled,reservation_status,reservation_status_date,arrival_date,arrival_date_week_number,diferencia_dias,stays_in_weekend_nights,stays_in_week_nights,country,is_repeated_guest,adults,children,babies,customer_type,days_in_waiting_list,lead_time,market_segment,distribution_channel,agent,company,reserved_room_type,assigned_room_type,meal,required_car_parking_spaces,total_of_special_requests,adr,overnight_stays,number_of_guests
20,Resort Hotel,0,0,1,0,Check-Out,2015-07-07,2015-07-01,27,6,2,4,PRT,0,2,0.0,0,Transient,0,72,Direct,Direct,250.0,NaN,A,A,BB,0,1,84.67,6,2.0
21,Resort Hotel,0,0,1,0,Check-Out,2015-07-07,2015-07-01,27,6,2,4,PRT,0,2,0.0,0,Transient,0,72,Direct,Direct,250.0,NaN,D,D,BB,0,1,99.67,6,2.0
23,Resort Hotel,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,2,5,PRT,0,2,0.0,0,Transient,0,78,Offline TA/TO,TA/TO,5.0,NaN,D,D,BB,1,0,63.60,7,2.0
24,Resort Hotel,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,2,5,IRL,0,2,0.0,0,Contract,0,48,Offline TA/TO,TA/TO,8.0,NaN,D,D,BB,0,0,79.50,7,2.0
26,Resort Hotel,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,2,5,PRT,0,2,0.0,0,Transient,0,77,Online TA,TA/TO,240.0,NaN,A,A,BB,0,0,94.00,7,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56255,City Hotel,0,0,0,1,No-Show,2015-11-12,2015-12-11,50,-29,2,5,AGO,0,1,0.0,0,Transient,0,2,Direct,Direct,NaN,NaN,E,E,BB,0,1,104.00,7,1.0
59793,City Hotel,0,5,0,1,No-Show,2016-09-11,2016-11-09,46,-59,0,1,PRT,1,1,0.0,0,Transient,0,6,Corporate,Corporate,NaN,219.0,D,D,BB,0,1,94.00,1,1.0
61857,City Hotel,0,10,0,1,No-Show,2016-02-11,2016-11-02,45,-265,0,1,PRT,1,1,0.0,0,Transient,0,26,Corporate,Corporate,NaN,219.0,A,E,BB,0,1,88.00,1,1.0
75076,City Hotel,0,1,0,1,No-Show,2017-01-02,2017-02-01,5,-30,0,0,AUT,1,1,0.0,0,Transient,0,1,Aviation,Corporate,NaN,153.0,A,A,BB,0,1,0.00,0,1.0
85609,City Hotel,0,0,0,1,No-Show,2017-02-08,2017-08-02,31,-175,0,2,PRT,1,1,0.0,0,Transient,0,0,Corporate,Corporate,NaN,40.0,A,C,BB,0,1,65.00,2,1.0

In [26]:
# reordenamos las columnas 
df_final = df_final[['hotel', 
                        'market_segment', 
                        'distribution_channel',
                        'agent', 
                        'company',
                        'previous_cancellations',
                        'previous_bookings_not_canceled', 
                        'booking_changes',               
                        'is_canceled', 
                        'reservation_status', 
                        'reservation_status_date', 
                        'arrival_date',
                        'arrival_date_week_number',
                        'diferencia_dias',

                        'overnight_stays',
                        'stays_in_weekend_nights',
                        'stays_in_week_nights',
                        
                        'country', 
                        'is_repeated_guest', 
                        'adults', 
                        'children',
                        'babies',
                        'number_of_guests',
                        'customer_type', 
                        'days_in_waiting_list', 
                        'lead_time',    
                        
                        'reserved_room_type',
                        'assigned_room_type', 
                        'meal', 
                        'required_car_parking_spaces', 
                        'total_of_special_requests',
 
                        'adr']]

df_final

,hotel,market_segment,distribution_channel,agent,company,previous_cancellations,previous_bookings_not_canceled,booking_changes,is_canceled,reservation_status,reservation_status_date,arrival_date,arrival_date_week_number,diferencia_dias,overnight_stays,stays_in_weekend_nights,stays_in_week_nights,country,is_repeated_guest,adults,children,babies,number_of_guests,customer_type,days_in_waiting_list,lead_time,reserved_room_type,assigned_room_type,meal,required_car_parking_spaces,total_of_special_requests,adr
20,Resort Hotel,Direct,Direct,250.0,NaN,0,0,1,0,Check-Out,2015-07-07,2015-07-01,27,6,6,2,4,PRT,0,2,0.0,0,2.0,Transient,0,72,A,A,BB,0,1,84.67
21,Resort Hotel,Direct,Direct,250.0,NaN,0,0,1,0,Check-Out,2015-07-07,2015-07-01,27,6,6,2,4,PRT,0,2,0.0,0,2.0,Transient,0,72,D,D,BB,0,1,99.67
23,Resort Hotel,Offline TA/TO,TA/TO,5.0,NaN,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,7,2,5,PRT,0,2,0.0,0,2.0,Transient,0,78,D,D,BB,1,0,63.60
24,Resort Hotel,Offline TA/TO,TA/TO,8.0,NaN,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,7,2,5,IRL,0,2,0.0,0,2.0,Contract,0,48,D,D,BB,0,0,79.50
26,Resort Hotel,Online TA,TA/TO,240.0,NaN,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,7,2,5,PRT,0,2,0.0,0,2.0,Transient,0,77,A,A,BB,0,0,94.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56255,City Hotel,Direct,Direct,NaN,NaN,0,0,0,1,No-Show,2015-11-12,2015-12-11,50,-29,7,2,5,AGO,0,1,0.0,0,1.0,Transient,0,2,E,E,BB,0,1,104.00
59793,City Hotel,Corporate,Corporate,NaN,219.0,0,5,0,1,No-Show,2016-09-11,2016-11-09,46,-59,1,0,1,PRT,1,1,0.0,0,1.0,Transient,0,6,D,D,BB,0,1,94.00
61857,City Hotel,Corporate,Corporate,NaN,219.0,0,10,0,1,No-Show,2016-02-11,2016-11-02,45,-265,1,0,1,PRT,1,1,0.0,0,1.0,Transient,0,26,A,E,BB,0,1,88.00
75076,City Hotel,Aviation,Corporate,NaN,153.0,0,1,0,1,No-Show,2017-01-02,2017-02-01,5,-30,0,0,0,AUT,1,1,0.0,0,1.0,Transient,0,1,A,A,BB,0,1,0.00
85609,City Hotel,Corporate,Corporate,NaN,40.0,0,0,0,1,No-Show,2017-02-08,2017-08-02,31,-175,2,0,2,PRT,1,1,0.0,0,1.0,Transient,0,0,A,C,BB,0,1,65.00

## 6-Creacion de nuevas columnas con paises

In [27]:
import pycountry

def convert_iso_alpha3_to_country_name(iso_alpha3):
    """ la fucnion convierte el codigo iso alpha 3 a nombre de pais 

    Args:
        iso_alpha3 (str): codigo iso alpha 3 perteneciente a un pais

    Returns:
        str: nombre del pais
    """
    try:
        country = pycountry.countries.get(alpha_3=iso_alpha3)
        return country.name
    except:
        return np.nan

In [28]:
# aplicamos la funcion convert_iso_alpha3_to_country_name a la columna country
df_final["country"] = df_final["country"].apply(lambda x: convert_iso_alpha3_to_country_name(x))
df_final

,hotel,market_segment,distribution_channel,agent,company,previous_cancellations,previous_bookings_not_canceled,booking_changes,is_canceled,reservation_status,reservation_status_date,arrival_date,arrival_date_week_number,diferencia_dias,overnight_stays,stays_in_weekend_nights,stays_in_week_nights,country,is_repeated_guest,adults,children,babies,number_of_guests,customer_type,days_in_waiting_list,lead_time,reserved_room_type,assigned_room_type,meal,required_car_parking_spaces,total_of_special_requests,adr
20,Resort Hotel,Direct,Direct,250.0,NaN,0,0,1,0,Check-Out,2015-07-07,2015-07-01,27,6,6,2,4,Portugal,0,2,0.0,0,2.0,Transient,0,72,A,A,BB,0,1,84.67
21,Resort Hotel,Direct,Direct,250.0,NaN,0,0,1,0,Check-Out,2015-07-07,2015-07-01,27,6,6,2,4,Portugal,0,2,0.0,0,2.0,Transient,0,72,D,D,BB,0,1,99.67
23,Resort Hotel,Offline TA/TO,TA/TO,5.0,NaN,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,7,2,5,Portugal,0,2,0.0,0,2.0,Transient,0,78,D,D,BB,1,0,63.60
24,Resort Hotel,Offline TA/TO,TA/TO,8.0,NaN,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,7,2,5,Ireland,0,2,0.0,0,2.0,Contract,0,48,D,D,BB,0,0,79.50
26,Resort Hotel,Online TA,TA/TO,240.0,NaN,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,7,2,5,Portugal,0,2,0.0,0,2.0,Transient,0,77,A,A,BB,0,0,94.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56255,City Hotel,Direct,Direct,NaN,NaN,0,0,0,1,No-Show,2015-11-12,2015-12-11,50,-29,7,2,5,Angola,0,1,0.0,0,1.0,Transient,0,2,E,E,BB,0,1,104.00
59793,City Hotel,Corporate,Corporate,NaN,219.0,0,5,0,1,No-Show,2016-09-11,2016-11-09,46,-59,1,0,1,Portugal,1,1,0.0,0,1.0,Transient,0,6,D,D,BB,0,1,94.00
61857,City Hotel,Corporate,Corporate,NaN,219.0,0,10,0,1,No-Show,2016-02-11,2016-11-02,45,-265,1,0,1,Portugal,1,1,0.0,0,1.0,Transient,0,26,A,E,BB,0,1,88.00
75076,City Hotel,Aviation,Corporate,NaN,153.0,0,1,0,1,No-Show,2017-01-02,2017-02-01,5,-30,0,0,0,Austria,1,1,0.0,0,1.0,Transient,0,1,A,A,BB,0,1,0.00
85609,City Hotel,Corporate,Corporate,NaN,40.0,0,0,0,1,No-Show,2017-02-08,2017-08-02,31,-175,2,0,2,Portugal,1,1,0.0,0,1.0,Transient,0,0,A,C,BB,0,1,65.00

## 7-Creacion de columna con Geolocalizacion de los paises

In [29]:
lista_paises = list(df_final["country"].unique())

In [30]:
# importamos geopy 
from geopy.geocoders import Nominatim
import tqdm as tqdm

In [31]:
# creamos una instancia de Nominatim
geolocator = Nominatim(user_agent="my_app")

# creamos una funcion para obtener la latitud y longitud de un pais
def get_lat_lon(country):
    """ la funcion recibe un pais y devuelve la latitud y longitud


    Args:
        country (str): nombre del pais a buscar
    Returns:
        tuple: devuelve una tuple con la latitud y longitud
    """
    try:
        location = geolocator.geocode(country)
        return location.latitude, location.longitude
    except:
        return np.nan, np.nan

In [34]:
# creamos un diccionario con los paises y sus coordenadas 
diccionario_coordenadas = {}
for pais in lista_paises:
    lat, lon = get_lat_lon(pais)
    diccionario_coordenadas[pais] = [lat, lon]
    print(pais, lat, lon)

Portugal 39.6621648 -8.1353519
Ireland 52.865196 -7.9794599
nan 46.3144754 11.0480288
United Kingdom 54.7023545 -3.2765753
Romania 45.9852129 24.6859225
Spain 39.3260685 -4.8379791
Norway 61.1529386 8.7876653
Oman 21.0000287 57.0036901
Germany 51.1638175 10.4478313
France 46.603354 1.8883335
Switzerland 46.7985624 8.2319736
United States 39.7837304 -100.445882
Greece 38.9953683 21.9877132
Italy 42.6384261 12.674297
Netherlands 52.2434979 5.6343227
Denmark 55.670249 10.3333283
Argentina -34.9964963 -64.9672817
Russian Federation 64.6863136 97.7453061
Sweden 59.6749712 14.5208584
Poland 52.215933 19.134422
Australia -24.7761086 134.755
Estonia 58.7523778 25.3319078
Czechia 49.7439047 15.3381061
Brazil -10.3333333 -53.2
Belgium 50.6402809 4.6667145
Finland 63.2467777 25.9209164
Mozambique -19.302233 34.9144977
Botswana -23.1681782 24.5928742
Luxembourg 49.8158683 6.1296751
Slovenia 46.1199444 14.8153333
Albania 41.000028 19.9999619
India 22.3511148 78.6677428
China 35.000074 104.999927
Mexico 23.6585116 -102.0077097
Morocco 31.1728205 -7.3362482
Ukraine 49.4871968 31.2718321
Latvia 56.8406494 24.7537645
Puerto Rico 18.2247706 -66.4858295
Serbia 44.1534121 20.55144
Chile -31.7613365 -71.3187697
Belarus 53.4250605 27.6971358
South Africa -28.8166236 24.991639
Israel 30.8124247 34.8594762
Cayman Islands 19.703182249999998 -79.9174627243246
Zambia -14.5189121 27.5589884
Austria 47.59397 14.12456
Algeria 28.0000272 2.9999825
Korea, Republic of 55.8215537 49.132971
Lithuania 55.3500003 23.7499997
Costa Rica 10.2735633 -84.0739102
Hungary 47.1817585 19.5060937
Croatia 45.3658443 15.6575209
Iran, Islamic Republic of 32.6475314 54.5643516
Central African Republic 7.0323598 19.9981227
Cyprus 34.9823018 33.1451285
New Zealand -41.5000831 172.8344077
Indonesia -2.4833826 117.8902853
Kazakhstan 48.1012954 66.7780818
Thailand 14.8971921 100.83273
Colombia 4.099917 -72.9088133
Dominican Republic 19.0974031 -70.3028026
North Macedonia 41.6171214 21.7168387
Malaysia 4.5693754 102.2656823
Nigeria 9.6000359 7.9999721
Venezuela, Bolivarian Republic of 8.0018709 -66.1109318
Gibraltar 36.1285933 -5.3474761
Armenia 40.7696272 44.6736646
Turkey 38.9597594 34.9249653
Sri Lanka 7.877395849999999 80.66247852355892
Cuba 23.0131338 -80.8328748
Cameroon 4.6125522 13.1535811
Bosnia and Herzegovina 44.3053476 17.5961467
Mauritius -20.2759451 57.5703566
Comoros -12.2045176 44.2832964
Suriname 4.1413025 -56.0771187
Jamaica 18.1850507 -77.3947693
Uganda 1.5333554 32.2166578
Bulgaria 42.6073975 25.4856617
Côte d'Ivoire 7.9897371 -5.5679458
Jordan 31.1667049 36.941628
Syrian Arab Republic 34.6401861 39.0494106
Japan 36.5748441 139.2394179
Singapore 1.357107 103.8194992
Burundi -3.426449 29.9324519
Angola -11.8775768 17.5691241
Kuwait 29.2733964 47.4979476
Uruguay -32.8755548 -56.0201525
Lebanon 33.8750629 35.843409
Andorra 42.5407167 1.5732033
Viet Nam 15.9266657 107.9650855
Azerbaijan 40.3936294 47.7872508
Palau 5.3783537 132.9102573
Egypt 26.2540493 29.2675469
Slovakia 48.7411522 19.4528646
Cabo Verde 16.0000552 -24.0083947
Malta 35.8885993 14.4476911
Malawi -13.2687204 33.9301963
Ecuador -1.3397668 -79.3666965
Madagascar -18.9249604 46.4416422
Iceland 64.9841821 -18.1059013
Uzbekistan 41.32373 63.9528098
Zimbabwe -18.4554963 29.7468414
Nepal 28.1083929 84.0917139
Bahamas 24.7736546 -78.0000547
Maldives 3.7203503 73.2244152
Togo 8.7800265 1.0199765
Taiwan, Province of China nan nan
Hong Kong 22.2793278 114.1628131
Djibouti 11.8145966 42.8453061
Georgia 32.3293809 -83.1137366
Pakistan 30.3308401 71.247499
Tunisia 33.8439408 9.400138
Sao Tome and Principe 0.9713095 7.02255
Peru -6.8699697 -75.0458515
Saudi Arabia 25.6242618 42.3528328
Saint Kitts and Nevis 17.250512 -62.6725973
Ethiopia 10.2116702 38.6521203
Philippines 12.7503486 122.7312101
United Arab Emirates 24.0002488 53.9994829
Iraq 33.0955793 44.1749775
Rwanda -1.9646631 30.0644358
Myanmar 17.1750495 95.9999652
Burkina Faso 12.0753083 -1.6880314
Kenya 1.4419683 38.4313975
Monaco 43.7323492 7.4276832
Libya 26.8234472 18.1236723
Guinea-Bissau 11.815215 -15.2351044
Tanzania, United Republic of -6.5247123 35.7878438
Mali 16.3700359 -2.2900239
Bangladesh 24.4769288 90.2934413
Bahrain 26.1551249 50.5344606
Bolivia, Plurinational State of -17.0568696 -64.9912286
Seychelles -4.6574977 55.4540146
Qatar 25.3336984 51.2295295
Paraguay -23.3165935 -58.1693445
Barbados 13.1500331 -59.5250305
Anguilla 18.1954947 -63.0750234
El Salvador 13.8000382 -88.9140683
Gabon -0.8999695 11.6899699
French Polynesia -17.0243749 -144.6434898
Liechtenstein 47.1416307 9.5531527
Guyana 4.8417097 -58.6416891
Saint Lucia 13.8250489 -60.975036
Antarctica -79.4063075 0.3149312
Guatemala 15.5855545 -90.345759
Ghana 8.0300284 -1.0800271
American Samoa -14.297124 -170.7131481
Panama 8.559559 -81.1308434
Senegal 14.4750607 -14.4529612
Mauritania 20.2540382 -9.2399263
Aruba 12.51756625 -69.98186415210564
New Caledonia -21.3019905 165.4880773
Kiribati 0.3448612 173.6641773
Sudan 14.5844444 29.4917691
Tajikistan 38.6281733 70.8156541
Lao People's Democratic Republic 20.0171109 103.378253
Faroe Islands 62.0448724 -7.0322972
Jersey 49.2214561 -2.1358386
Guernsey 49.4566233 -2.5822348
Fiji -18.1239696 179.0122737
Honduras 15.2572432 -86.0755145
Cambodia 12.5433216 104.8144914
Isle of Man 54.1936805 -4.5591148
Nicaragua 12.6090157 -85.2936911
Benin 9.5293472 2.2584408
Virgin Islands, British nan nan
Guadeloupe 16.2528827 -61.5686855
Macao 22.1899448 113.5380454
Montenegro 42.9868853 19.5180992
Mayotte -12.825543 45.148490830203045

In [36]:
df_final["latitud"] = df_final["country"].apply(lambda x: diccionario_coordenadas[x][0])
df_final["longitud"] = df_final["country"].apply(lambda x: diccionario_coordenadas[x][1])

In [37]:
df_final

,hotel,market_segment,distribution_channel,agent,company,previous_cancellations,previous_bookings_not_canceled,booking_changes,is_canceled,reservation_status,reservation_status_date,arrival_date,arrival_date_week_number,diferencia_dias,overnight_stays,stays_in_weekend_nights,stays_in_week_nights,country,is_repeated_guest,adults,children,babies,number_of_guests,customer_type,days_in_waiting_list,lead_time,reserved_room_type,assigned_room_type,meal,required_car_parking_spaces,total_of_special_requests,adr,latitud,longitud
20,Resort Hotel,Direct,Direct,250.0,NaN,0,0,1,0,Check-Out,2015-07-07,2015-07-01,27,6,6,2,4,Portugal,0,2,0.0,0,2.0,Transient,0,72,A,A,BB,0,1,84.67,39.662165,-8.135352
21,Resort Hotel,Direct,Direct,250.0,NaN,0,0,1,0,Check-Out,2015-07-07,2015-07-01,27,6,6,2,4,Portugal,0,2,0.0,0,2.0,Transient,0,72,D,D,BB,0,1,99.67,39.662165,-8.135352
23,Resort Hotel,Offline TA/TO,TA/TO,5.0,NaN,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,7,2,5,Portugal,0,2,0.0,0,2.0,Transient,0,78,D,D,BB,1,0,63.60,39.662165,-8.135352
24,Resort Hotel,Offline TA/TO,TA/TO,8.0,NaN,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,7,2,5,Ireland,0,2,0.0,0,2.0,Contract,0,48,D,D,BB,0,0,79.50,52.865196,-7.979460
26,Resort Hotel,Online TA,TA/TO,240.0,NaN,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,7,2,5,Portugal,0,2,0.0,0,2.0,Transient,0,77,A,A,BB,0,0,94.00,39.662165,-8.135352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56255,City Hotel,Direct,Direct,NaN,NaN,0,0,0,1,No-Show,2015-11-12,2015-12-11,50,-29,7,2,5,Angola,0,1,0.0,0,1.0,Transient,0,2,E,E,BB,0,1,104.00,-11.877577,17.569124
59793,City Hotel,Corporate,Corporate,NaN,219.0,0,5,0,1,No-Show,2016-09-11,2016-11-09,46,-59,1,0,1,Portugal,1,1,0.0,0,1.0,Transient,0,6,D,D,BB,0,1,94.00,39.662165,-8.135352
61857,City Hotel,Corporate,Corporate,NaN,219.0,0,10,0,1,No-Show,2016-02-11,2016-11-02,45,-265,1,0,1,Portugal,1,1,0.0,0,1.0,Transient,0,26,A,E,BB,0,1,88.00,39.662165,-8.135352
75076,City Hotel,Aviation,Corporate,NaN,153.0,0,1,0,1,No-Show,2017-01-02,2017-02-01,5,-30,0,0,0,Austria,1,1,0.0,0,1.0,Transient,0,1,A,A,BB,0,1,0.00,47.593970,14.124560
85609,City Hotel,Corporate,Corporate,NaN,40.0,0,0,0,1,No-Show,2017-02-08,2017-08-02,31,-175,2,0,2,Portugal,1,1,0.0,0,1.0,Transient,0,0,A,C,BB,0,1,65.00,39.662165,-8.135352

In [39]:
# reordenamos las columnas 
df_final = df_final[['hotel', 
                    'market_segment', 
                    'distribution_channel',
                    'agent', 
                    'company',
                    'previous_cancellations',
                    'previous_bookings_not_canceled', 
                    'booking_changes',               
                    'is_canceled', 
                    'reservation_status', 
                    'reservation_status_date', 
                    'arrival_date',
                    'arrival_date_week_number',
                    'diferencia_dias',

                    'overnight_stays',
                    'stays_in_weekend_nights',
                    'stays_in_week_nights',
                    
                    'country', 
                    'latitud',
                    'longitud',
                    'is_repeated_guest', 
                    'adults', 
                    'children',
                    'babies',
                    'number_of_guests',
                    'customer_type', 
                    'days_in_waiting_list', 
                    'lead_time',    
                    
                    'reserved_room_type',
                    'assigned_room_type', 
                    'meal', 
                    'required_car_parking_spaces', 
                    'total_of_special_requests',
                    
                    'adr']]

df_final

,hotel,market_segment,distribution_channel,agent,company,previous_cancellations,previous_bookings_not_canceled,booking_changes,is_canceled,reservation_status,reservation_status_date,arrival_date,arrival_date_week_number,diferencia_dias,overnight_stays,stays_in_weekend_nights,stays_in_week_nights,country,latitud,longitud,is_repeated_guest,adults,children,babies,number_of_guests,customer_type,days_in_waiting_list,lead_time,reserved_room_type,assigned_room_type,meal,required_car_parking_spaces,total_of_special_requests,adr
20,Resort Hotel,Direct,Direct,250.0,NaN,0,0,1,0,Check-Out,2015-07-07,2015-07-01,27,6,6,2,4,Portugal,39.662165,-8.135352,0,2,0.0,0,2.0,Transient,0,72,A,A,BB,0,1,84.67
21,Resort Hotel,Direct,Direct,250.0,NaN,0,0,1,0,Check-Out,2015-07-07,2015-07-01,27,6,6,2,4,Portugal,39.662165,-8.135352,0,2,0.0,0,2.0,Transient,0,72,D,D,BB,0,1,99.67
23,Resort Hotel,Offline TA/TO,TA/TO,5.0,NaN,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,7,2,5,Portugal,39.662165,-8.135352,0,2,0.0,0,2.0,Transient,0,78,D,D,BB,1,0,63.60
24,Resort Hotel,Offline TA/TO,TA/TO,8.0,NaN,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,7,2,5,Ireland,52.865196,-7.979460,0,2,0.0,0,2.0,Contract,0,48,D,D,BB,0,0,79.50
26,Resort Hotel,Online TA,TA/TO,240.0,NaN,0,0,0,0,Check-Out,2015-08-07,2015-07-01,27,37,7,2,5,Portugal,39.662165,-8.135352,0,2,0.0,0,2.0,Transient,0,77,A,A,BB,0,0,94.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56255,City Hotel,Direct,Direct,NaN,NaN,0,0,0,1,No-Show,2015-11-12,2015-12-11,50,-29,7,2,5,Angola,-11.877577,17.569124,0,1,0.0,0,1.0,Transient,0,2,E,E,BB,0,1,104.00
59793,City Hotel,Corporate,Corporate,NaN,219.0,0,5,0,1,No-Show,2016-09-11,2016-11-09,46,-59,1,0,1,Portugal,39.662165,-8.135352,1,1,0.0,0,1.0,Transient,0,6,D,D,BB,0,1,94.00
61857,City Hotel,Corporate,Corporate,NaN,219.0,0,10,0,1,No-Show,2016-02-11,2016-11-02,45,-265,1,0,1,Portugal,39.662165,-8.135352,1,1,0.0,0,1.0,Transient,0,26,A,E,BB,0,1,88.00
75076,City Hotel,Aviation,Corporate,NaN,153.0,0,1,0,1,No-Show,2017-01-02,2017-02-01,5,-30,0,0,0,Austria,47.593970,14.124560,1,1,0.0,0,1.0,Transient,0,1,A,A,BB,0,1,0.00
85609,City Hotel,Corporate,Corporate,NaN,40.0,0,0,0,1,No-Show,2017-02-08,2017-08-02,31,-175,2,0,2,Portugal,39.662165,-8.135352,1,1,0.0,0,1.0,Transient,0,0,A,C,BB,0,1,65.00

In [40]:
# guardamos el dataframe en un csv
df_final.to_csv("data/finanzas-hotel-bookings-limpio.csv", index=False)